# Generated by Django 4.2.1 on 2024-03-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aidetect", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="humanhelth",
            name="anomaly_message",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
