# Generated by Django 4.2.1 on 2024-03-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aidetect", "0002_humanhelth_anomaly_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirstStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="first_step/")),
            ],
        ),
    ]
