# Generated by Django 4.2.1 on 2024-03-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aidetect", "0003_firststep"),
    ]

    operations = [
        migrations.AddField(
            model_name="firststep",
            name="detected_emotion",
            field=models.CharField(default=2),
            preserve_default=False,
        ),
    ]
